### ISSUE TITLE
Write all tests

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-garden-build-py#1]
- [ ] test everything
- [x] add coverage reporting integration with CodeClimate.

**Comment by jseppi** [comment]
I added coverage to the default pytest call in #7. Not quite sure the best way to add `cc-test-reporter`. Will have to do some more research on using locally built docker images on CircleCi.

**Comment by jseppi** [comment]
Woot, think I got the coverage stuff figured out in #8

**Comment by jmhooper** [comment]
https://github.com/18F/federalist-garden-build/issues/82
