### ISSUE TITLE
Explore/add New Relic process monitoring

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-garden-build-py#10]
Not totally sure if this is possible, but adding New Relic to monitor processes and collect errors might be a good idea. 

The reasons I'm not totally sure about it working are 
1) this is not a web app, 
2) the containers are "ephemeral", 
3) the containers sleep after each use, which might end up being kinda funky in NR, and 
4) since sub-commands are basically shell'd out, I'm not sure if NR could "globally" track anything in them.

**Comment by wslack** [comment]
Moved to https://github.com/18F/federalist-garden-build/issues/79
