### ISSUE TITLE
Capture and handle exception when an S3 key is invalid

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-garden-build-py#11]
If the timing is just "right", a publish step could take place right after S3 keys are auto-rotated, which will cause the publish to fail. This happened with a federalist-docs build on 11/13/17 at around 11:50PM: https://federalist-staging.18f.gov/sites/60/builds/3104/logs

The salient part of the error logs was:

```
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.
```

We should be able to catch the `ClientError` and at least provide a better error to the user. I'm thinking something along the lines of

> Whoops, our S3 keys were rotated during your build and became out of date. This was not a problem with your site build, but if you restart the failed build it should work on the next try. Sorry for the inconvenience!

**Comment by wslack** [comment]
That error message sounds great!

**Comment by jseppi** [comment]
So....a problem I've encountered here is that the way the `main` task works is that it basically shells out to sub-tasks, and does NOT call them within Python. The reasoning behind this is described at https://github.com/18F/federalist-garden-build-py/blob/master/tasks/main.py#L128-L137 (it's a known deficiency in pyinvoke, basically).

That means we can't do regular python `try...except` handling from subtasks to the `main` task.

The way I think we can still accomplish this is to make the `except` handler for `UnexpectedExit` in `main` do some string matching on the error message that the shelled-out command result has in its `stderr`, ie, check for `"InvalidAccessKeyId"` in the error message.

(wanted to type this out as I thought about it)

**Comment by wslack** [comment]
That makes sense. I would think you would always want to pass up the error message as a string that can be displayed or searched.
