### ISSUE TITLE
When GITHUB_TOKEN is <nil>, log output is full of "[PRIVATE VALUE HIDDEN]"

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-garden-build-py#12]
When a new build starts with a blank/nil/empty `GITHUB_TOKEN` env var, the `replace_private_values()` function replaces every instance of `''` with `'[PRIVATE VALUE HIDDEN]'`, making the logs totally unreadable.

Fix: check that `GITHUB_TOKEN` is defined before adding it to the list of private values that are stripped from log output.

**Comment by jseppi** [comment]
@jmhooper: when is it the case that `GITHUB_TOKEN` is empty? Should a build even be run when that happens?

**Comment by jmhooper** [comment]
That happens when a user who has not joined Federalist pushes a commit. We use the token for the committing user. Since they're not on Federalist, we don't have a token.

**Comment by jseppi** [comment]
Ok, cool, and we should still attempt a build, right?

**Comment by jmhooper** [comment]
Yep!

**Comment by wslack** [comment]
And display their GitHub name in the logs - everyone benefits from the repo being added.

**Comment by jseppi** [comment]
The build container doesn't receive the GitHub username from the builder right now, so that will need to be a separate feature issue IMHO.

**Comment by wslack** [comment]
How does that work now? I thought it saved the name from the inbound hook?

**Comment by jseppi** [comment]
The Federalist web app keeps track of the user who initiated a build. It's just that that info isn't sent to the build container currently (the github username isn't needed for cloning or for anything else in the build process).

**Comment by wslack** [comment]
Ohhhh - I should have been clearer. The way the names are now is fine - showing up in the webapp. The builder doesn't need to know that.

**Comment by jseppi** [comment]
Sweet!
